"""add notification settings and expiry tracking

Revision ID: 6fd58a772ef1
Revises: 80f4c8b35e48
Create Date: 2026-08-22 18:03:25.578824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd58a772ef1'
down_revision: Union[str, Sequence[str], None] = '80f4c8b35e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('smtp_password_wrap_meta', sa.JSON(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_from_address', sa.String(length=255), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('telegram_bot_token_wrap_meta', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_notified_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('expiry_notified_at')

    op.drop_table('notification_config')
    # ### end Alembic commands ###
