"""initial schema

Revision ID: a9124e3f8ff9
Revises: 
Create Date: 2026-08-13 22:29:38.522211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9124e3f8ff9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cert_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('key_usage', sa.JSON(), nullable=False),
    sa.Column('extended_key_usage', sa.JSON(), nullable=False),
    sa.Column('basic_constraints', sa.String(length=64), nullable=False),
    sa.Column('max_validity_days', sa.Integer(), nullable=False),
    sa.Column('allowed_san_types', sa.JSON(), nullable=False),
    sa.Column('requires_email', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('certificate_authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ROOT', 'INTERMEDIATE', name='catype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject_dn', sa.String(length=500), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=True),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('key_wrap_meta', sa.JSON(), nullable=True),
    sa.Column('public_key_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_ca_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'EXPIRED', 'REVOKED', 'SUPERSEDED', name='castatus', native_enum=False), nullable=False),
    sa.Column('crl_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saml_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('idp_entity_id', sa.String(length=500), nullable=True),
    sa.Column('idp_sso_url', sa.String(length=500), nullable=True),
    sa.Column('idp_slo_url', sa.String(length=500), nullable=True),
    sa.Column('idp_x509_cert', sa.Text(), nullable=True),
    sa.Column('sp_entity_id', sa.String(length=500), nullable=True),
    sa.Column('attribute_map', sa.JSON(), nullable=True),
    sa.Column('group_role_map', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tls_listener_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('SELF_SIGNED', 'UPLOADED', 'ISSUED_BY_INTERMEDIATE', name='tlssource', native_enum=False), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('private_key_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('key_wrap_meta', sa.JSON(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_source', sa.Enum('LOCAL', 'SAML', name='authsource', native_enum=False), nullable=False),
    sa.Column('saml_name_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saml_name_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_prefix'), ['token_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('crl_issuances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('crl_number', sa.Integer(), nullable=False),
    sa.Column('crl_pem', sa.Text(), nullable=False),
    sa.Column('this_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crl_issuances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crl_issuances_ca_id'), ['ca_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_token_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'TOKEN', 'SYSTEM', name='actortype', native_enum=False), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['actor_token_id'], ['api_tokens.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ca_id', sa.Integer(), nullable=False),
    sa.Column('serial_hex', sa.String(length=32), nullable=False),
    sa.Column('profile_code', sa.String(length=32), nullable=False),
    sa.Column('subject_dn', sa.String(length=500), nullable=False),
    sa.Column('sans', sa.JSON(), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('csr_pem', sa.Text(), nullable=False),
    sa.Column('public_key_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', 'EXPIRED', name='certificatestatus', native_enum=False), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('issued_via', sa.Enum('UI', 'API', name='issuedvia', native_enum=False), nullable=False),
    sa.Column('api_token_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_token_id'], ['api_tokens.id'], ),
    sa.ForeignKeyConstraint(['ca_id'], ['certificate_authorities.id'], ),
    sa.ForeignKeyConstraint(['profile_code'], ['cert_profiles.code'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_ca_id'), ['ca_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_serial_hex'), ['serial_hex'], unique=True)

    op.create_table('revocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revocations')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_serial_hex'))
        batch_op.drop_index(batch_op.f('ix_certificates_ca_id'))

    op.drop_table('certificates')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    op.drop_table('user_roles')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    op.drop_table('role_permissions')
    with op.batch_alter_table('crl_issuances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crl_issuances_ca_id'))

    op.drop_table('crl_issuances')
    op.drop_table('app_settings')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_prefix'))

    op.drop_table('api_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tls_listener_config')
    op.drop_table('saml_config')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('certificate_authorities')
    op.drop_table('cert_profiles')
    # ### end Alembic commands ###
