"""add log forwarding config

Revision ID: b47753bbf61b
Revises: 6fd58a772ef1
Create Date: 2026-08-23 17:15:53.823392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47753bbf61b'
down_revision: Union[str, Sequence[str], None] = '6fd58a772ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_forwarding_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_log_min_level', sa.String(length=16), nullable=False),
    sa.Column('hec_enabled', sa.Boolean(), nullable=False),
    sa.Column('hec_send_app_logs', sa.Boolean(), nullable=False),
    sa.Column('hec_send_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('hec_url', sa.String(length=500), nullable=True),
    sa.Column('hec_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('hec_token_wrap_meta', sa.JSON(), nullable=True),
    sa.Column('hec_source', sa.String(length=255), nullable=True),
    sa.Column('hec_sourcetype', sa.String(length=255), nullable=True),
    sa.Column('hec_index', sa.String(length=255), nullable=True),
    sa.Column('hec_verify_tls', sa.Boolean(), nullable=False),
    sa.Column('syslog_enabled', sa.Boolean(), nullable=False),
    sa.Column('syslog_send_app_logs', sa.Boolean(), nullable=False),
    sa.Column('syslog_send_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('syslog_host', sa.String(length=255), nullable=True),
    sa.Column('syslog_port', sa.Integer(), nullable=False),
    sa.Column('syslog_protocol', sa.String(length=16), nullable=False),
    sa.Column('syslog_facility', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_forwarding_config')
    # ### end Alembic commands ###
